### ISSUE TITLE
java.util.NoSuchElementException: No value present

### ISSUE THREAD

**Issue by muro1214** [muro1214/IzunaSystem#13]
```
Exception in thread "pool-1-thread-1" java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:148)
        at izunasystem.io.file.JsonLoader.getLatestRecordingFile(JsonLoader.java:102)
        at izunasystem.io.file.FileRenamer.changeFilename(FileRenamer.java:49)
        at izunasystem.io.file.FileRenamer.printRecordedFileInfo(FileRenamer.java:21)
        at izunasystem.listener.IzunaListener.lambda$checkBattleEnd$1(IzunaListener.java:124)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by muro1214** [comment]
かんたん
